---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/home
  label: Home
  create: all
- path: content/post
  label: Post
  create: all
- path: content/talk
  label: Talk
  create: all
- path: content/publication
  label: Publication
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
